name: Debug Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Thêm tmate action vào đây để tạm dừng và mở SSH
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        
      - name: Bước tiếp theo (sẽ chạy sau khi thoát tmate)
        run: echo "Done debugging!"
